### ISSUE TITLE
Inline language declaration throws unknown language

### ISSUE THREAD

**Issue by aronduby** [bebraw/highlight-loader#15]
I'm using this with the markdown and html loaders as shown in the examples here. However, if my markdown code block uses inline language declaration then it throws errors about an unknown language.

```
ERROR in ./src/components/switch/docs/readme.md
Module build failed: Error: Unknown language: "language-typescript"
    at highlight (C:\dev\WebCommon-HtmlShare\node_modules\highlight.js\lib\highlight.js:494:13)
    at highlightCode (C:\dev\WebCommon-HtmlShare\node_modules\highlight-loader\index.js:50:12)
    at Object.<anonymous> (C:\dev\WebCommon-HtmlShare\node_modules\highlight-loader\index.js:38:12)
    at initialize.<anonymous> (C:\dev\WebCommon-HtmlShare\node_modules\cheerio\lib\api\manipulation.js:275:74)
    at exports.domEach (C:\dev\WebCommon-HtmlShare\node_modules\cheerio\lib\utils.js:52:24)
    at initialize.exports.replaceWith (C:\dev\WebCommon-HtmlShare\node_modules\cheerio\lib\api\manipulation.js:268:3)
    at Object.module.exports (C:\dev\WebCommon-HtmlShare\node_modules\highlight-loader\index.js:25:13)
 @ ./src/components/switch/docs/index.ts 4:0-48 4:0-48
 @ ./src/docs.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/docs.ts
i ｢wdm｣: Failed to compile.
```

the portion causing the problem in the md file:
```
```typescript
import { Switch } from '@salespad/html-share';
const switch = new Switch(document.getElementById('switch-example'));
/```
```

and the relevant portion of the config:
```
{
          test: /\.md$/,
          loader: 'html-loader!highlight-loader!markdown-loader'
}
```

**Comment by bebraw** [comment]
I think we have to upgrade the project to use the newest version of highlight.js to get TypeScript support. The version we are using might not have it causing the error. A PR is welcome. 👍

**Comment by aronduby** [comment]
@bebraw nope, just a change in the markdown, see the PR

**Comment by bebraw** [comment]
@aronduby Ok, added a comment. Once that's addressed, we can merge. 👍
